import { ChatSummary, ChatMessage, StatusContact, CallRecord, WalletTransaction, UserProfile } from '../types';

export const INITIAL_USER: UserProfile = {
  id: 'current_user',
  name: 'Lilo Banim',
  phone: '+27 82 123 4567',
  email: 'lilobanim60@gmail.com',
  bio: 'Hey there! I am using Blue Chats.',
  isOnline: true,
};

export const INITIAL_CHATS: ChatSummary[] = [
  {
    id: 'c1',
    name: 'Naledi M.',
    isGroup: false,
    participants: ['current_user', 'naledi'],
    avatarColor: '#2453D6',
    lastMessage: 'Sent you a voice note',
    lastMessageType: 'voice',
    lastMessageTime: '09:41',
    lastMessageTimestamp: Date.now() - 1000 * 60 * 15,
    unreadCount: 2,
    mine: false,
    online: true,
  },
  {
    id: 'c2',
    name: 'Family 👨‍👩‍👧‍👦',
    isGroup: true,
    participants: ['current_user', 'naledi', 'thabo', 'mom'],
    avatarColor: '#E8A23B',
    lastMessage: 'Thabo: see you at 6',
    lastMessageType: 'text',
    lastMessageTime: '09:12',
    lastMessageTimestamp: Date.now() - 1000 * 60 * 45,
    unreadCount: 5,
    mine: false,
    online: true,
  },
  {
    id: 'c3',
    name: 'Kabelo',
    isGroup: false,
    participants: ['current_user', 'kabelo'],
    avatarColor: '#3B6BFA',
    lastMessage: 'You: Sharp, sending the file now',
    lastMessageType: 'text',
    lastMessageTime: '08:50',
    lastMessageTimestamp: Date.now() - 1000 * 60 * 70,
    unreadCount: 0,
    mine: true,
    online: false,
  },
  {
    id: 'c4',
    name: 'Rea',
    isGroup: false,
    participants: ['current_user', 'rea'],
    avatarColor: '#4DD8E8',
    lastMessage: '📍 Location shared: Rosebank Mall',
    lastMessageType: 'text',
    lastMessageTime: 'Yesterday',
    lastMessageTimestamp: Date.now() - 1000 * 60 * 60 * 24,
    unreadCount: 0,
    mine: false,
    online: true,
  },
  {
    id: 'c5',
    name: 'Work Squad',
    isGroup: true,
    participants: ['current_user', 'lindiwe', 'boss'],
    avatarColor: '#8A6CF2',
    lastMessage: 'Lindiwe: standup moved to 10am',
    lastMessageType: 'text',
    lastMessageTime: 'Yesterday',
    lastMessageTimestamp: Date.now() - 1000 * 60 * 60 * 28,
    unreadCount: 1,
    mine: false,
    online: false,
  },
  {
    id: 'c6',
    name: 'Mom',
    isGroup: false,
    participants: ['current_user', 'mom'],
    avatarColor: '#2FBE8F',
    lastMessage: 'You: Love you too ❤️',
    lastMessageType: 'text',
    lastMessageTime: 'Mon',
    lastMessageTimestamp: Date.now() - 1000 * 60 * 60 * 72,
    unreadCount: 0,
    mine: true,
    online: false,
  },
];

export const INITIAL_MESSAGES: Record<string, ChatMessage[]> = {
  c1: [
    {
      id: 'm1-1',
      chatId: 'c1',
      senderId: 'naledi',
      senderName: 'Naledi M.',
      type: 'text',
      text: 'Hey! Are you still joining for the weekend road trip?',
      timestamp: Date.now() - 1000 * 60 * 60 * 2,
      timeFormatted: '08:15',
      status: 'read',
      mine: false,
    },
    {
      id: 'm1-2',
      chatId: 'c1',
      senderId: 'current_user',
      senderName: 'Me',
      type: 'text',
      text: 'Yes definitely! Packing right now. What time are we meeting?',
      timestamp: Date.now() - 1000 * 60 * 50,
      timeFormatted: '08:35',
      status: 'read',
      mine: true,
    },
    {
      id: 'm1-3',
      chatId: 'c1',
      senderId: 'naledi',
      senderName: 'Naledi M.',
      type: 'voice',
      text: 'Voice note (0:14)',
      mediaUrl: 'https://actions.google.com/sounds/v1/water/rain_heavy.ogg',
      mediaDuration: 14,
      timestamp: Date.now() - 1000 * 60 * 15,
      timeFormatted: '09:41',
      status: 'delivered',
      mine: false,
    },
  ],
  c3: [
    {
      id: 'm3-1',
      chatId: 'c3',
      senderId: 'kabelo',
      senderName: 'Kabelo',
      type: 'text',
      text: 'Do you have the video recording from the shoot?',
      timestamp: Date.now() - 1000 * 60 * 90,
      timeFormatted: '08:20',
      status: 'read',
      mine: false,
    },
    {
      id: 'm3-2',
      chatId: 'c3',
      senderId: 'current_user',
      senderName: 'Me',
      type: 'text',
      text: 'Sharp, sending the file now via Bunny.net',
      timestamp: Date.now() - 1000 * 60 * 70,
      timeFormatted: '08:50',
      status: 'read',
      mine: true,
    },
  ],
};

export const INITIAL_STATUS_CONTACTS: StatusContact[] = [
  {
    id: 's1',
    name: 'Naledi M.',
    avatarColor: '#2453D6',
    items: [
      {
        id: 'st-1',
        type: 'text',
        text: 'Sunday market run 🍊',
        bg: '#2453D6',
        timestamp: Date.now() - 1000 * 60 * 90,
        timeFormatted: '2h ago',
        views: 24,
      },
      {
        id: 'st-2',
        type: 'text',
        text: 'This coffee though ☕️',
        bg: '#8A6CF2',
        timestamp: Date.now() - 1000 * 60 * 60,
        timeFormatted: '1h ago',
        views: 31,
      },
      {
        id: 'st-3',
        type: 'text',
        text: 'Golden hour on the way home ✨',
        bg: '#34B3A0',
        timestamp: Date.now() - 1000 * 60 * 20,
        timeFormatted: '20m ago',
        views: 45,
      },
    ],
  },
  {
    id: 's2',
    name: 'Kabelo',
    avatarColor: '#3B6BFA',
    items: [
      {
        id: 'st-4',
        type: 'text',
        text: 'New PB at the gym 💪 120kg bench!',
        bg: '#3B6BFA',
        timestamp: Date.now() - 1000 * 60 * 180,
        timeFormatted: '3h ago',
        views: 19,
      },
    ],
  },
  {
    id: 's3',
    name: 'Family 👨‍👩‍👧‍👦',
    avatarColor: '#E8A23B',
    items: [
      {
        id: 'st-5',
        type: 'text',
        text: 'Braai day! Come through 🔥🥩',
        bg: '#E8A23B',
        timestamp: Date.now() - 1000 * 60 * 300,
        timeFormatted: '5h ago',
        views: 52,
      },
      {
        id: 'st-6',
        type: 'text',
        text: 'Thabo doing the meat as usual',
        bg: '#2453D6',
        timestamp: Date.now() - 1000 * 60 * 240,
        timeFormatted: '4h ago',
        views: 58,
      },
      {
        id: 'st-7',
        type: 'text',
        text: 'Best sunny day ever in Joburg ☀️',
        bg: '#4DD8E8',
        timestamp: Date.now() - 1000 * 60 * 120,
        timeFormatted: '2h ago',
        views: 64,
      },
    ],
  },
];

export const SPONSORED_ADS = [
  {
    sponsor: 'Bleushorts',
    text: 'Your shorts, movies & sounds — all in one app.',
    cta: 'Open Bleushorts',
    bg: '#101C42',
  },
  {
    sponsor: 'MTN SA',
    text: 'Double data weekends are back. 10GB for R99.',
    cta: 'Get the deal',
    bg: '#152657',
  },
  {
    sponsor: 'Takealot',
    text: 'Big Friday drops end tonight. Free delivery on orders over R450.',
    cta: 'Shop now',
    bg: '#0B1330',
  },
];

export const INITIAL_CALLS: CallRecord[] = [
  {
    id: 'call-1',
    partnerId: 'naledi',
    partnerName: 'Naledi M.',
    avatarColor: '#2453D6',
    type: 'video',
    direction: 'incoming',
    timestamp: Date.now() - 1000 * 60 * 35,
    timeFormatted: 'Today, 09:15',
    durationSeconds: 242,
  },
  {
    id: 'call-2',
    partnerId: 'kabelo',
    partnerName: 'Kabelo',
    avatarColor: '#3B6BFA',
    type: 'voice',
    direction: 'outgoing',
    timestamp: Date.now() - 1000 * 60 * 60 * 5,
    timeFormatted: 'Today, 04:30',
    durationSeconds: 78,
  },
  {
    id: 'call-3',
    partnerId: 'mom',
    partnerName: 'Mom',
    avatarColor: '#2FBE8F',
    type: 'video',
    direction: 'missed',
    timestamp: Date.now() - 1000 * 60 * 60 * 26,
    timeFormatted: 'Yesterday, 14:10',
    durationSeconds: 0,
  },
  {
    id: 'call-4',
    partnerId: 'rea',
    partnerName: 'Rea',
    avatarColor: '#4DD8E8',
    type: 'voice',
    direction: 'incoming',
    timestamp: Date.now() - 1000 * 60 * 60 * 48,
    timeFormatted: 'Tuesday, 18:22',
    durationSeconds: 512,
  },
];

export const INITIAL_TRANSACTIONS: WalletTransaction[] = [
  {
    id: 'tx-1',
    title: 'Naledi M.',
    subtitle: 'Split dinner at Tashas',
    amount: -185.50,
    type: 'debit',
    timestamp: Date.now() - 1000 * 60 * 60 * 4,
    timeFormatted: 'Today, 08:30',
    category: 'payment',
  },
  {
    id: 'tx-2',
    title: 'Top up from FNB',
    subtitle: 'Instant EFT Deposit',
    amount: 1500.00,
    type: 'credit',
    timestamp: Date.now() - 1000 * 60 * 60 * 28,
    timeFormatted: 'Yesterday',
    category: 'deposit',
  },
  {
    id: 'tx-3',
    title: 'Kabelo',
    subtitle: 'Gym smoothie contribution',
    amount: 65.00,
    type: 'credit',
    timestamp: Date.now() - 1000 * 60 * 60 * 52,
    timeFormatted: '2 days ago',
    category: 'transfer',
  },
  {
    id: 'tx-4',
    title: 'Woolworths Food',
    subtitle: 'Tap to Pay in store',
    amount: -342.20,
    type: 'debit',
    timestamp: Date.now() - 1000 * 60 * 60 * 96,
    timeFormatted: '3 days ago',
    category: 'payment',
  },
];

export const FIND_FRIENDS_SUGGESTIONS = [
  { name: 'Zanele K.', sub: 'Also nearby · Joined this week', color: '#8A6CF2' },
  { name: 'Sipho D.', sub: '3 mutual contacts', color: '#4DD8E8' },
  { name: 'Amahle R.', sub: 'Also nearby in Sandton', color: '#E8A23B' },
  { name: 'Bongani T.', sub: '2 mutual contacts', color: '#2FBE8F' },
];
